name: Compile and upload CV and resumé
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  compile:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install b2
      - uses: typst-community/setup-typst@v3
        with:
          typst-version: '0.12'
      - name: Compile academic CV
        run: typst compile cv.typ david-lougheed-cv.pdf
      - name: Compile resumé
        run: typst compile resume.typ david-lougheed-resume.pdf
      - name: Upload artifacts to B2
        run: |
          b2 file upload davidlougheed-public david-lougheed-cv.pdf david-lougheed-cv.pdf
          b2 file upload davidlougheed-public david-lougheed-resume.pdf david-lougheed-resume.pdf
        env:
          B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}
          B2_APPLICATION_KEY_ID: ${{ secrets.B2_APPLICATION_KEY_ID }}
